### ISSUE TITLE
When superuser clicks on "Edit license" button, in the background an unknown error occurs

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1289]

**Comment by wfenrich** [comment]
![image](https://user-images.githubusercontent.com/8678301/94068868-0c62c780-fdf0-11ea-8820-316f56525743.png)

**Comment by madryk** [comment]
Most probable cause:
```
[2021-05-19T17:32:05.318+0000] [glassfish 4.1] [WARNING] [] [javax.enterprise.resource.webcontainer.jsf.lifecycle] [tid: _ThreadID=25 _ThreadName=http-listener-1(1)] [timeMillis: 1621445525318] [levelValue: 900] [[
  #{LicenseListingPage.licenseForEdit(license)}: javax.el.MethodNotFoundException: /dashboard-licenses.xhtml @87,93 action="#{LicenseListingPage.licenseForEdit(license)}": Method licenseForEdit not found
javax.faces.FacesException: #{LicenseListingPage.licenseForEdit(license)}: javax.el.MethodNotFoundException: /dashboard-licenses.xhtml @87,93 action="#{LicenseListingPage.licenseForEdit(license)}": Method licenseForEdit not found
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:110)
        at javax.faces.component.UICommand.broadcast(UICommand.java:315)
        at javax.faces.component.UIData.broadcast(UIData.java:1108)
        at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
        at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
        at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:413)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
Caused by: javax.faces.el.MethodNotFoundException: javax.el.MethodNotFoundException: /dashboard-licenses.xhtml @87,93 action="#{LicenseListingPage.licenseForEdit(license)}": Method licenseForEdit not found
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:91)
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)
        ... 46 more
Caused by: javax.el.MethodNotFoundException: /dashboard-licenses.xhtml @87,93 action="#{LicenseListingPage.licenseForEdit(license)}": Method licenseForEdit not found
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:109)
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87)
        ... 47 more
]]
```
