### ISSUE TITLE
Can't move a Dataverse containing datasets

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1316]

**Comment by wfenrich** [comment]
Operation ends up with an unknown error. 

Moving works fine when I try to move an empty, unpublished Dataverse.

**Comment by madryk** [comment]
```
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
	at java.util.Vector.forEach(Vector.java:1275)
	at edu.harvard.iq.dataverse.engine.command.impl.MoveDataverseCommand.executeImpl(MoveDataverseCommand.java:95)
	at edu.harvard.iq.dataverse.engine.command.AbstractVoidCommand.execute(AbstractVoidCommand.java:29)
	at edu.harvard.iq.dataverse.engine.command.AbstractVoidCommand.execute(AbstractVoidCommand.java:1)
	at edu.harvard.iq.dataverse.EjbDataverseEngine.submit(EjbDataverseEngine.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
