### ISSUE TITLE
When trying to create a harvesting client, an unknown error occurs

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1410]
![image](https://user-images.githubusercontent.com/8678301/106826983-4c806380-6688-11eb-822e-1df6f7a4fd7c.png)

**Comment by wfenrich** [comment]
![image](https://user-images.githubusercontent.com/8678301/106827034-5d30d980-6688-11eb-9324-9122175a2caf.png)

**Comment by madryk** [comment]
```
2021-02-04T11:30:25.205+0000|Warning: #{harvestingClientsPage.validateInitialSettings()}: java.lang.NoSuchMethodError: org.hamcrest.CoreMatchers.allOf(Lorg/hamcrest/Matcher;Lorg/hamcrest/Matcher;)Lorg/hamcrest/Matcher;
javax.faces.FacesException: #{harvestingClientsPage.validateInitialSettings()}: java.lang.NoSuchMethodError: org.hamcrest.CoreMatchers.allOf(Lorg/hamcrest/Matcher;Lorg/hamcrest/Matcher;)Lorg/hamcrest/Matcher;
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:118)
	at javax.faces.component.UICommand.broadcast(UICommand.java:315)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:305)
```
```
Caused by: java.lang.NoSuchMethodError: org.hamcrest.CoreMatchers.allOf(Lorg/hamcrest/Matcher;Lorg/hamcrest/Matcher;)Lorg/hamcrest/Matcher;
	at com.lyncode.xoai.serviceprovider.parsers.MetadataFormatParser.metadataElement(MetadataFormatParser.java:67)
	at com.lyncode.xoai.serviceprovider.parsers.MetadataFormatParser.hasNext(MetadataFormatParser.java:48)
	at com.lyncode.xoai.serviceprovider.handler.ListMetadataFormatsHandler.handle(ListMetadataFormatsHandler.java:48)
	at com.lyncode.xoai.serviceprovider.ServiceProvider.listMetadataFormats(ServiceProvider.java:49)
	at edu.harvard.iq.dataverse.harvest.client.oai.OaiHandler.runListMetadataFormats(OaiHandler.java:185)
	at edu.harvard.iq.dataverse.harvest.client.HarvestingClientsPage.validateServerUrlOAI(HarvestingClientsPage.java:481)
	at edu.harvard.iq.dataverse.harvest.client.HarvestingClientsPage.validateInitialSettings(HarvestingClientsPage.java:542)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.el.ELUtil.invokeMethod(ELUtil.java:332)
	at javax.el.BeanELResolver.invoke(BeanELResolver.java:537)
	at javax.el.CompositeELResolver.invoke(CompositeELResolver.java:256)
	at com.sun.el.parser.AstValue.invoke(AstValue.java:283)
	at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
```
