### ISSUE TITLE
Can't remove draft if we already have downloaded full set of files within it.

### ISSUE THREAD

**Issue by madryk** [CeON/fairchive#1647]
```
Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.1.v20150605-31e8258): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: update or delete on table "dataset" violates foreign key constraint "downloaddatasetlog_dataset_id_fkey" on table "downloaddatasetlog"
  Detail: Key (id)=(2088) is still referenced from table "downloaddatasetlog".
Error Code: 0
Call: DELETE FROM DATASET WHERE (ID = ?)
        bind => [1 parameter bound]
Query: DeleteObjectQuery([Dataset id:2088 ])
        at org.eclipse.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:879)
        at org.eclipse.persistence.internal.jpa.QueryImpl.performPreQueryFlush(QueryImpl.java:967)
        at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:207)
        at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:521)
        at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:400)
        at edu.harvard.iq.dataverse.DataverseDao.findRootDataverse(DataverseDao.java:163)
        at sun.reflect.GeneratedMethodAccessor117.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by dbojanek** [comment]
Error occurred while deleting dataset which is usually doable only if this dataset wasn't released yet.
However any attempt to delete dataset after `whole dataset download` has been made would end up with this error.
