### ISSUE TITLE
Editing a dataset in multiple tabs causes errors when rejecting

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#2188]
```
Caused by: javax.persistence.OptimisticLockException: Exception [EclipseLink-5010] (Eclipse Persistence Services - 2.6.1.v20150605-31e8258): org.eclipse.persistence.exceptions.$
Exception Description: The object [[DatasetVersion id:723]] cannot be merged because it has changed or been deleted since it was last read.
Class> edu.harvard.iq.dataverse.persistence.dataset.DatasetVersion
        at org.eclipse.persistence.internal.jpa.EntityManagerImpl.mergeInternal(EntityManagerImpl.java:555)
        at org.eclipse.persistence.internal.jpa.EntityManagerImpl.merge(EntityManagerImpl.java:530)
        at com.sun.enterprise.container.common.impl.EntityManagerWrapper.merge(EntityManagerWrapper.java:305)
        at edu.harvard.iq.dataverse.engine.command.impl.ReturnDatasetToAuthorCommand.execute(ReturnDatasetToAuthorCommand.java:48)
        at edu.harvard.iq.dataverse.engine.command.impl.ReturnDatasetToAuthorCommand.execute(ReturnDatasetToAuthorCommand.java:20)
```

**Comment by wfenrich** [comment]
1. User sends a dataset for review. 
2. Reviewer opens the dataset in Tab 1 and then another copy in Tab 2. 
3. Reviewer edit some metadata in Tab 2 and saves the draft. 
4. Reviewer goes back to Tab 1 and returns the dataset for modification. 

Result: 

1) Reviewer is given an error message informing that the dataset has changed. 
2) The dataset unlocks. 
3) Reviewer is given a message saying that the dataset is unlocked.  
4) No notification is sent to the user (so s/he is not informed that the dataset has been sent back and that s/he should take some actions). 
5) The index is not refreshed, so on search results the dataset is still marked with "In review" badge. 

Expected behavior: 

An error means an error – the reviewer should be given error message  (1), but no further actions (2+) should take place. If s/he refreshes the page, s/he will be able to retry sending back to review.
