### ISSUE TITLE
Sign Up page is not displayed

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#2361]
```
[2023-04-21T08:42:20.407+0000] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.error.FallbackExceptionHandler] [tid: _ThreadID=27 _ThreadName=http-listener-1(1)] [timeMillis: 1682066540407] [levelValue: 1000] [[
  /dataverseuser.xhtml @623,125 disabled="#{DataverseUserPage.isDisabledForEdit(editableField.NAME)}": javax.ejb.EJBException
javax.el.ELException: /dataverseuser.xhtml @623,125 disabled="#{DataverseUserPage.isDisabledForEdit(editableField.NAME)}": javax.ejb.EJBException
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:114)
        at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:194)
        at javax.faces.component.html.HtmlInputText.isDisabled(HtmlInputText.java:212)
        at org.primefaces.component.inputtext.InputTextRenderer.createStyleClass(InputTextRenderer.java:115)
        at org.primefaces.component.inputtext.InputTextRenderer.encodeMarkup(InputTextRenderer.java:101)
        at org.primefaces.component.inputtext.InputTextRenderer.encodeEnd(InputTextRenderer.java:62)
...
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.el.ELUtil.invokeMethod(ELUtil.java:332)
        ... 86 more
Caused by: java.lang.NullPointerException
        at edu.harvard.iq.dataverse.authorization.AuthenticationServiceBean.lookupProvider(AuthenticationServiceBean.java:416)
        at sun.reflect.GeneratedMethodAccessor1096.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)```

**Comment by wfenrich** [comment]
![image](https://user-images.githubusercontent.com/8678301/233602882-b91413f1-956e-4c70-b5e0-b0a9f42fafe2.png)
