### ISSUE TITLE
PDB API metadata importer is broken

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#2431]
In MX-RDR we allow users to import metadata values from various sources, including PDB API. Unfortunatelly, this importer does not want to cooperate (again): 

![image](https://github.com/CeON/dataverse/assets/8678301/8256cd2d-8f95-4fe4-b8d9-3b81cd7bf6e4)

**Comment by diasf** [comment]
Observed error:

```
[2024-03-21T11:31:44.520+0000] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.importers.ui.ImporterForm] [tid: _ThreadID=32 _ThreadName=http-listener-1(3)] [timeMillis: 1711020704520] [levelValue: 900] [[
  Exception during importer invocation
java.lang.NullPointerException
        at pl.edu.icm.pl.mxrdr.extension.importer.pdb.PdbDataContainer.init(PdbDataContainer.java:63)
        at pl.edu.icm.pl.mxrdr.extension.importer.pdb.PdbApiImporter.fetchMetadata(PdbApiImporter.java:73)
        at edu.harvard.iq.dataverse.importers.ui.ImporterForm.nextStep(ImporterForm.java:156)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

```

**Comment by diasf** [comment]
Missing `pdbx_vrpt_summary` element in the response resulted in a `NullPointerException` when trying to extract nested `data_completeness` field.
