### ISSUE TITLE
Check what's wrong with unparseable date issue in logs (while on search page)

### ISSUE THREAD

**Issue by madryk** [CeON/fairchive#53]

**Comment by madryk** [comment]
```
2019-03-05T12:01:52.578+0100|Severe: java.text.ParseException: Unparseable date: "2019-03-05"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at edu.harvard.iq.dataverse.util.DateUtil.formatDate(DateUtil.java:40)
	at edu.harvard.iq.dataverse.search.SolrSearchResult.getDateToDisplayOnCard(SolrSearchResult.java:889)
	at sun.reflect.GeneratedMethodAccessor221.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:363)
	at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176)
	at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203)
	at com.sun.el.parser.AstValue.getValue(AstValue.java:140)
	at com.sun.el.parser.AstValue.getValue(AstValue.java:204)
	at com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:226)
```

When retreving from search dataset document with date:
```
"dateFriendly":"2019-03-05",
```

Code comments suggest that dateFriendly should be in form: 
```
    /**
     * i.e. "Mar 17, 2015"
     */
    public static final String RELEASE_OR_CREATE_DATE_SEARCHABLE_TEXT = "dateFriendly";
```

**Comment by madryk** [comment]
Issue maybe is related to different date formatting in polish language
